# Use root/example as user/password credentials
version: '3.1'

services:

  local_mysql:
    image:  mysql:5.7
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: airflow
    ports:
      - "3306:3306"
    volumes:
        - ./ci/mysql/conf.d/airflow.cnf:/etc/mysql/conf.d/my.cnf    
        # - ./ci/mysql/conf.d/airflow.cnf:/etc/mysql/mysql.conf.d/my.cnf 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8123:8123